-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 14:18:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Teller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teller` (
  `id` INT NOT NULL,
  `tell_name` VARCHAR(55) NULL,
  `tell_address` VARCHAR(45) NULL,
  `tell_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `id` INT NOT NULL,
  `cli_name` VARCHAR(55) NULL,
  `cli_address` VARCHAR(45) NULL,
  `cli_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bank` (
  `id` INT NOT NULL,
  `bank_name` VARCHAR(45) NULL,
  `bank_address` VARCHAR(60) NULL,
  `Client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Client_id`),
  INDEX `fk_Bank_Client1_idx` (`Client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Bank_Client1`
    FOREIGN KEY (`Client_id`)
    REFERENCES `mydb`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teller_has_Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teller_has_Client` (
  `Teller_id` INT NOT NULL,
  `Client_id` INT NOT NULL,
  PRIMARY KEY (`Teller_id`, `Client_id`),
  INDEX `fk_Teller_has_Client_Client1_idx` (`Client_id` ASC) VISIBLE,
  INDEX `fk_Teller_has_Client_Teller_idx` (`Teller_id` ASC) VISIBLE,
  CONSTRAINT `fk_Teller_has_Client_Teller`
    FOREIGN KEY (`Teller_id`)
    REFERENCES `mydb`.`Teller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teller_has_Client_Client1`
    FOREIGN KEY (`Client_id`)
    REFERENCES `mydb`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `id` INT NOT NULL,
  `pay_type` VARCHAR(45) NULL,
  `pay_address` VARCHAR(45) NULL,
  `Client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Client_id`),
  INDEX `fk_Payment_Client1_idx` (`Client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_Client1`
    FOREIGN KEY (`Client_id`)
    REFERENCES `mydb`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Withdrawal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Withdrawal` (
  `id` INT NOT NULL,
  `with_amount` VARCHAR(45) NULL,
  `with_date` DATE NULL,
  `with_time` TIME NULL,
  `Teller_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Teller_id`),
  INDEX `fk_Withdrawal_Teller1_idx` (`Teller_id` ASC) VISIBLE,
  CONSTRAINT `fk_Withdrawal_Teller1`
    FOREIGN KEY (`Teller_id`)
    REFERENCES `mydb`.`Teller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Deposit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Deposit` (
  `id` INT NOT NULL,
  `dep_amount` VARCHAR(45) NULL,
  `dep_amount` VARCHAR(45) NULL,
  `dep_date` DATE NULL,
  `dep_time` VARCHAR(45) NULL,
  `Depositcol` TIME NULL,
  `Teller_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Teller_id`),
  INDEX `fk_Deposit_Teller1_idx` (`Teller_id` ASC) VISIBLE,
  CONSTRAINT `fk_Deposit_Teller1`
    FOREIGN KEY (`Teller_id`)
    REFERENCES `mydb`.`Teller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `id` INT NOT NULL,
  `acc_name` VARCHAR(45) NULL,
  `acc_desc` VARCHAR(45) NULL,
  `Client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Client_id`),
  INDEX `fk_Account_Client1_idx` (`Client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Account_Client1`
    FOREIGN KEY (`Client_id`)
    REFERENCES `mydb`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Slip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Slip` (
  `id` INT NOT NULL,
  `slip_size` VARCHAR(45) NULL,
  `slip_date` VARCHAR(45) NULL,
  `Client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Client_id`),
  INDEX `fk_Slip_Client1_idx` (`Client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Slip_Client1`
    FOREIGN KEY (`Client_id`)
    REFERENCES `mydb`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Investment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Investment` (
  `id` INT NOT NULL,
  `inv_type` VARCHAR(45) NULL,
  `inv_date` DATE NULL,
  `inv` DATE NULL,
  `Client_id` INT NOT NULL,
  `Teller_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Client_id`, `Teller_id`),
  INDEX `fk_Investment_Client1_idx` (`Client_id` ASC) VISIBLE,
  INDEX `fk_Investment_Teller1_idx` (`Teller_id` ASC) VISIBLE,
  CONSTRAINT `fk_Investment_Client1`
    FOREIGN KEY (`Client_id`)
    REFERENCES `mydb`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Investment_Teller1`
    FOREIGN KEY (`Teller_id`)
    REFERENCES `mydb`.`Teller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loan` (
  `id` INT NOT NULL,
  `loan_amt` VARCHAR(45) NULL,
  `loan_date` DATE NULL,
  `loan_type` VARCHAR(45) NULL,
  `Client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Client_id`),
  INDEX `fk_Loan_Client1_idx` (`Client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Loan_Client1`
    FOREIGN KEY (`Client_id`)
    REFERENCES `mydb`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`car` (
  `car_color` VARCHAR(45) NULL,
  `car_model` VARCHAR(45) NULL,
  `car_plate` VARCHAR(45) NULL,
  `Loan_id` INT NOT NULL,
  `Loan_Client_id` INT NOT NULL,
  PRIMARY KEY (`Loan_id`, `Loan_Client_id`),
  CONSTRAINT `fk_car_Loan1`
    FOREIGN KEY (`Loan_id` , `Loan_Client_id`)
    REFERENCES `mydb`.`Loan` (`id` , `Client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`home`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`home` (
  `loan_id` INT NOT NULL,
  `home_address` VARCHAR(45) NULL DEFAULT NULL,
  `home_color` VARCHAR(45) NULL DEFAULT NULL,
  `home_building` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`loan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personal` (
  `loan_id` INT NOT NULL,
  `personal_address` VARCHAR(45) NULL DEFAULT NULL,
  `personal_name` VARCHAR(45) NULL DEFAULT NULL,
  `personalcol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`loan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`loan` (
  `loan_id` INT NOT NULL,
  `loan_amt` VARCHAR(45) NULL DEFAULT NULL,
  `loan_date` VARCHAR(45) NULL DEFAULT NULL,
  `car_loan_id` INT NOT NULL,
  `home_loan_id` INT NOT NULL,
  `personal_loan_id` INT NOT NULL,
  PRIMARY KEY (`loan_id`, `car_loan_id`, `home_loan_id`, `personal_loan_id`),
  INDEX `fk_loan_car_idx` (`car_loan_id` ASC) VISIBLE,
  INDEX `fk_loan_home1_idx` (`home_loan_id` ASC) VISIBLE,
  INDEX `fk_loan_personal1_idx` (`personal_loan_id` ASC) VISIBLE,
  CONSTRAINT `fk_loan_car`
    FOREIGN KEY (`car_loan_id`)
    REFERENCES `mydb`.`car` (`loan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loan_home1`
    FOREIGN KEY (`home_loan_id`)
    REFERENCES `mydb`.`home` (`loan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loan_personal1`
    FOREIGN KEY (`personal_loan_id`)
    REFERENCES `mydb`.`personal` (`loan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fixed income sec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fixed income sec` (
  `inv_id` INT NOT NULL,
  `fixed_date` DATE NULL DEFAULT NULL,
  `fixed_payment` INT(11) NULL DEFAULT NULL,
  `fixed_rate` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`inv_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`uitf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uitf` (
  `inv_id` INT NOT NULL,
  `uitf_amt` INT(11) NULL DEFAULT NULL,
  `uitf_rate` DECIMAL(5,2) NULL DEFAULT NULL,
  `uitf_desc` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`inv_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sb capital market`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sb capital market` (
  `inv_id` INT NOT NULL,
  `sb_income` INT(11) NULL DEFAULT NULL,
  `sb_rate` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`inv_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`investment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`investment` (
  `inv_id` INT NOT NULL,
  `inv_amt` VARCHAR(45) NULL DEFAULT NULL,
  `inv_type` VARCHAR(45) NULL DEFAULT NULL,
  `inv_date` DATE NULL DEFAULT NULL,
  `investmentcol` VARCHAR(45) NULL DEFAULT NULL,
  `fixed income sec_inv_id` INT NOT NULL,
  `uitf_inv_id` INT NOT NULL,
  `sb capital market_inv_id` INT NOT NULL,
  PRIMARY KEY (`inv_id`, `fixed income sec_inv_id`, `uitf_inv_id`, `sb capital market_inv_id`),
  INDEX `fk_investment_fixed income sec1_idx` (`fixed income sec_inv_id` ASC) VISIBLE,
  INDEX `fk_investment_uitf1_idx` (`uitf_inv_id` ASC) VISIBLE,
  INDEX `fk_investment_sb capital market1_idx` (`sb capital market_inv_id` ASC) VISIBLE,
  CONSTRAINT `fk_investment_fixed income sec1`
    FOREIGN KEY (`fixed income sec_inv_id`)
    REFERENCES `mydb`.`fixed income sec` (`inv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investment_uitf1`
    FOREIGN KEY (`uitf_inv_id`)
    REFERENCES `mydb`.`uitf` (`inv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investment_sb capital market1`
    FOREIGN KEY (`sb capital market_inv_id`)
    REFERENCES `mydb`.`sb capital market` (`inv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`car` (
  `car_color` VARCHAR(45) NULL,
  `car_model` VARCHAR(45) NULL,
  `car_plate` VARCHAR(45) NULL,
  `Loan_id` INT NOT NULL,
  `Loan_Client_id` INT NOT NULL,
  PRIMARY KEY (`Loan_id`, `Loan_Client_id`),
  CONSTRAINT `fk_car_Loan1`
    FOREIGN KEY (`Loan_id` , `Loan_Client_id`)
    REFERENCES `mydb`.`Loan` (`id` , `Client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Home`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Home` (
  `home_address` VARCHAR(45) NULL,
  `home_color` VARCHAR(45) NULL,
  `home_building` VARCHAR(45) NULL,
  `Loan_id` INT NOT NULL,
  `Loan_Client_id` INT NOT NULL,
  PRIMARY KEY (`Loan_id`, `Loan_Client_id`),
  CONSTRAINT `fk_Home_Loan1`
    FOREIGN KEY (`Loan_id` , `Loan_Client_id`)
    REFERENCES `mydb`.`Loan` (`id` , `Client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personal` (
  `personal_address` VARCHAR(45) NULL,
  `personal_name` VARCHAR(45) NULL,
  `Loan_id` INT NOT NULL,
  `Loan_Client_id` INT NOT NULL,
  PRIMARY KEY (`Loan_id`, `Loan_Client_id`),
  CONSTRAINT `fk_Personal_Loan1`
    FOREIGN KEY (`Loan_id` , `Loan_Client_id`)
    REFERENCES `mydb`.`Loan` (`id` , `Client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Unit Investment Trust Fund`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Unit Investment Trust Fund` (
  `uitf_amount` INT NULL,
  `uitf_rate` DECIMAL(5,2) NULL,
  `uitf_desc` VARCHAR(45) NULL,
  `Investment_id` INT NOT NULL,
  `Investment_Client_id` INT NOT NULL,
  `Investment_Teller_id` INT NOT NULL,
  PRIMARY KEY (`Investment_id`, `Investment_Client_id`, `Investment_Teller_id`),
  CONSTRAINT `fk_Unit Investment Trust Fund_Investment1`
    FOREIGN KEY (`Investment_id` , `Investment_Client_id` , `Investment_Teller_id`)
    REFERENCES `mydb`.`Investment` (`id` , `Client_id` , `Teller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SB Capital Market`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SB Capital Market` (
  `sb_income` INT NULL,
  `sb_rate` DECIMAL(5,2) NULL,
  `Investment_id` INT NOT NULL,
  `Investment_Client_id` INT NOT NULL,
  `Investment_Teller_id` INT NOT NULL,
  PRIMARY KEY (`Investment_id`, `Investment_Client_id`, `Investment_Teller_id`),
  CONSTRAINT `fk_SB Capital Market_Investment1`
    FOREIGN KEY (`Investment_id` , `Investment_Client_id` , `Investment_Teller_id`)
    REFERENCES `mydb`.`Investment` (`id` , `Client_id` , `Teller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fixed Income Securities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fixed Income Securities` (
  `fixed_date` DATE NULL,
  `fixed_payment` INT NULL,
  `fixed_rate` DECIMAL(5,2) NULL,
  `Investment_id` INT NOT NULL,
  `Investment_Client_id` INT NOT NULL,
  `Investment_Teller_id` INT NOT NULL,
  PRIMARY KEY (`Investment_id`, `Investment_Client_id`, `Investment_Teller_id`),
  CONSTRAINT `fk_Fixed Income Securities_Investment1`
    FOREIGN KEY (`Investment_id` , `Investment_Client_id` , `Investment_Teller_id`)
    REFERENCES `mydb`.`Investment` (`id` , `Client_id` , `Teller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
